// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plvklrmatrgetpugfiwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsdmtscm1hdHJnZXRwdWdmaXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTM2OTcsImV4cCI6MjA1OTc4OTY5N30.bodh7_jGybkNkWPeSd0DPnh0Q5XGY06RFpW6R0gSPiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);